// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAR24BgIcTEoiPRmfC_28RBoaC9cLdto',
    appId: '1:617941647039:web:d2bf27f09f74d4c067900a',
    messagingSenderId: '617941647039',
    projectId: 'jikjjang-app',
    authDomain: 'jikjjang-app.firebaseapp.com',
    storageBucket: 'jikjjang-app.firebasestorage.app',
    measurementId: 'G-F87S6353CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrKE_RkJov5wSjLKSf9PCQPwTaUm7CR8',
    appId: '1:617941647039:android:7588d5ecd71ecdb667900a',
    messagingSenderId: '617941647039',
    projectId: 'jikjjang-app',
    storageBucket: 'jikjjang-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrxY9NsLZ6SmrIg2RpMen2iYS1Z08kug',
    appId: '1:617941647039:ios:20c16ec7a14e313867900a',
    messagingSenderId: '617941647039',
    projectId: 'jikjjang-app',
    storageBucket: 'jikjjang-app.firebasestorage.app',
    androidClientId: '617941647039-b5i1jvg0b34mpr8iqbeum7bbaeh5e7qu.apps.googleusercontent.com',
    iosClientId: '617941647039-lqbsq8s8t0u3sqekvo73arpgdfakst8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.jikjjangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrxY9NsLZ6SmrIg2RpMen2iYS1Z08kug',
    appId: '1:617941647039:ios:20c16ec7a14e313867900a',
    messagingSenderId: '617941647039',
    projectId: 'jikjjang-app',
    storageBucket: 'jikjjang-app.firebasestorage.app',
    androidClientId: '617941647039-b5i1jvg0b34mpr8iqbeum7bbaeh5e7qu.apps.googleusercontent.com',
    iosClientId: '617941647039-lqbsq8s8t0u3sqekvo73arpgdfakst8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.jikjjangApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfAR24BgIcTEoiPRmfC_28RBoaC9cLdto',
    appId: '1:617941647039:web:0f85c0c8bd18b4f267900a',
    messagingSenderId: '617941647039',
    projectId: 'jikjjang-app',
    authDomain: 'jikjjang-app.firebaseapp.com',
    storageBucket: 'jikjjang-app.firebasestorage.app',
    measurementId: 'G-K6KS7CFSSB',
  );
}
